name: Telegram Stock Bot

on:
  schedule:
    - cron: '0 4 * * *'   
    - cron: '30 8 * * *'  
  workflow_dispatch:      

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests nsepython

      - name: Run stock bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python3 -c "
import os
os.environ['bot_token'] = '${{ secrets.TELEGRAM_BOT_TOKEN }}'
os.environ['chat_id'] = '${{ secrets.TELEGRAM_CHAT_ID }}'
from stock_bot import get_stock_prices
get_stock_prices()
"
