name: Telegram Stock Bot

on:
  schedule:
    - cron: '0 4 * * *'    # 9:30 AM IST
    - cron: '30 8 * * *'   # 2:00 PM IST
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        env:
          XLSXNSE_BOT_TOKEN: ${{ secrets.XLSXNSE_BOT_TOKEN }}
          XLSXNSE_CHAT_ID: ${{ secrets.XLSXNSE_CHAT_ID }}
